[hbl_config]
; 홈브류 메뉴 기동 설정 - 8개까지 지정 가능[0-7].
; path=hbl.nsp 경로.
; program_id_#,=PID/TID
; override_address_space_#=39_bit, override_any_app_address_space=39_bit
; override_key_#=오버라이드 키 설정 !(원클릭)
; override_any_app=false - 비활성화, true - 활성화
; override_any_app_key=타이틀 오버라이드 키 설정 !(원클릭), 기본값 R+A
override_any_app=true
override_any_app_key=A
path=atmosphere/hb/hbl.nsp
program_id_0=010000000000100D
program_id_1=01E2044444AB9000
override_key=A
override_key_1=!A

[default_config]
override_key=!L
cheat_enable_key=L